# Generated by Django 2.2.7 on 2020-02-15 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=200, verbose_name='Имя персонажа')),
                ('person_photo', models.ImageField(blank=True, upload_to='img', verbose_name='Изображение персонажа')),
                ('person_author', models.CharField(max_length=50, verbose_name='Автор персонажа')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='PersonHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_title', models.CharField(max_length=200, verbose_name='Заголовок истории')),
                ('history_text', models.TextField(verbose_name='Текст Истории')),
                ('history_photo', models.ImageField(blank=True, upload_to='img', verbose_name='Изображения истории')),
                ('history_author', models.CharField(max_length=50, verbose_name='Автор истории')),
                ('history_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации истории')),
                ('person_add', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coolstory.Person', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
    ]
