# Generated by Django 2.2.7 on 2020-02-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='join_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('info_text', models.TextField(verbose_name='Текст')),
            ],
        ),
    ]
