# Generated by Django 2.2.7 on 2020-02-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200213_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_photo',
            field=models.ImageField(blank=True, upload_to='img/', verbose_name='Главное изображение'),
        ),
    ]
